# Generated by Django 5.0.6 on 2024-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalenTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='certifications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experience',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='job_post',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='location_constraint',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='max_salary_expected',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='min_salary_expected',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='salary_constraint',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='work_history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='work_shift',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='work_shift_constraint',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
