# Generated by Django 5.0.6 on 2024-05-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalenTrack', '0002_jobseeker_certifications_jobseeker_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecruiter',
            name='certificates_constraint',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='certifications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='experience_constraint',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='experience_reqd',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='job_post',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='qualifications_constraint',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='qualifications_reqd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='salary_provided',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='skills_constraint',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='skills_reqd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobrecruiter',
            name='work_shift',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
