# Generated by Django 5.0.6 on 2024-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalenTrack', '0004_jobseeker_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='max_salary_expected',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
