# Generated by Django 5.0.6 on 2024-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalenTrack', '0005_remove_jobseeker_max_salary_expected_jobseeker_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecruiter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
