# Generated by Django 5.0.6 on 2024-05-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalenTrack', '0006_jobrecruiter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecruiter',
            name='selected_seekers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='applied_jobs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
