# Generated by Django 5.0.6 on 2024-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalenTrack', '0007_jobrecruiter_selected_seekers_jobseeker_applied_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecruiter',
            name='experience_reqd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrecruiter',
            name='salary_provided',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='min_salary_expected',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
