# Generated by Django 5.0.6 on 2024-06-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalenTrack', '0008_alter_jobrecruiter_experience_reqd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecruiter',
            name='removed_seekers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='removed_jobs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobrecruiter',
            name='selected_seekers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='applied_jobs',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
