# Generated by Django 5.0.6 on 2024-06-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalenTrack', '0009_jobrecruiter_removed_seekers_jobseeker_removed_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecruiter',
            name='faq_document',
            field=models.FileField(blank=True, null=True, upload_to='faq_documents/'),
        ),
    ]
