# models.py
from django.db import models 
from django.contrib.auth.models import AbstractUser

class JobSeeker(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    name = models.CharField(max_length=100,null = True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    age = models.IntegerField(null=True, blank=True) 
    gender = models.CharField(max_length=1,null=True, blank=True) 
    description = models.TextField(null = True)
    job_post = models.CharField(max_length=100,null = True)
    qualifications = models.TextField(null = True)
    skills = models.TextField(null = True)
    experience = models.IntegerField(null = True,blank=True)
    work_history = models.TextField(null = True)
    min_salary_expected = models.IntegerField(blank=True,null = True)
    salary_constraint = models.CharField(max_length=20,null = True)
    certifications = models.TextField(null = True)
    location = models.CharField(max_length=50,null = True)
    location_constraint = models.CharField(max_length=20,null = True)
    work_shift = models.CharField(max_length=50,null = True)
    work_shift_constraint = models.CharField(max_length=20,null = True)
    applied_jobs = models.CharField(max_length=200,null = True)
    removed_jobs = models.CharField(max_length=200,null=True)

class JobRecruiter(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    name = models.CharField(max_length=100,null = True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    description = models.TextField(null = True)
    job_post = models.CharField(max_length=100,null = True)
    qualifications_reqd = models.TextField(null = True)
    qualifications_constraint = models.CharField(max_length=20,null = True)
    skills_reqd = models.TextField(null = True)
    skills_constraint = models.CharField(max_length=20,null = True)
    experience_reqd = models.IntegerField(null = True,blank=True)
    experience_constraint = models.CharField(max_length=20,null = True)
    salary_provided = models.IntegerField(blank=True,null = True)
    certifications = models.TextField(null = True)
    certificates_constraint = models.CharField(max_length=20,null = True)
    location = models.CharField(max_length=50,null = True)
    work_shift = models.CharField(max_length=50,null = True)
    selected_seekers = models.CharField(max_length=200,null = True)
    removed_seekers = models.CharField(max_length=200,null=True)
    faq_document = models.FileField(upload_to='faq_documents/', blank=True, null=True)
